/* eslint-disable linebreak-style */
export const hostUrl = {
  ifPortal: 'https://portal',
  localPortal: 'http://localhost:3000/',
  localSalesHub: 'http://localhost:3001/',
  localCampaign: 'http://localhost:3002/',
};

export const AppBelong = {
  salesHub: 'saleshub account rep',
  manager: 'alliance manager',
  campaign: 'campaign hub',
};

export const BannerLabels = {
  content: `"When Sales and Marketing adopt an Account-Based Strategy, Organizations Report Improved Results"`,
  tagLine: 'Gartner Account Based Benchmark Report',
};

export const ButtonLabels = {
  continue: 'Continue',
  cancel: 'Cancel',
  previous: 'Previous',
  previewAndSave: 'Preview and save',
  update: 'Update',
  addAsset: 'Add Assets',
  add: 'Add',
  delete: 'Delete',
  save: 'Save',
  search: 'Search',
  back: '< Back to the previous page',
  sendInvite: 'Send invite',
  submit: 'Submit',
  export: 'Export',
};

export const MenuBarLabels = {
  deletePartnership: 'Delete Partnership',
  addPartnershipButton: 'Add Partnership',
  confirmDelete: 'Are you sure you want to delete the Partnership?',
  cancelButton: ' Cancel',
  deleteButton: 'Delete',
  snackbarMsg: 'Partnership deleted successfully !',
};

export const SignInLabels = {
  signInlabel: 'Sign in',
  email: 'Email',
  password: 'Password',
  rememberMe: 'Remember me',
  signUpLabel: `Don't have an account?`,
  signUpButton: 'Sign up',
  forgotPassword: 'Forgot password?',
};
export const SignUpLabels = {
  createAccount: 'Create Account',
  accountSetupContent: 'Setup your account and start Co - selling',
  alreadyHaveAccount: 'Already have an account?',
  firstName: 'First name',
  lastName: 'Last name',
  workEmail: 'Work email',
  agreeTxt: 'I agree to the',
  termsAndConditions: 'terms & conditions',
  password: 'Password',
  signInlabel: 'Sign in',
  signUpButton: 'Sign up',
  companyName: 'Company name',
  role: 'Role',
  salesRegion: 'Sales region',
};
export const InviteLabels = {
  inviteHeader: 'Thank you for accepting the invite',
  inviteSubHeader: 'You are part of the Account Team',
  inviteContent: 'You will receive regular updates on the account',
  inviteSignup: 'Learn more about the partnership?',
  signUp: 'Sign up',
};

export const VerifyMailLabels = {
  verifyEmail: 'Verify your email',
  emailSentTxt: 'We’ve sent a verification link to your email',
  address: 'address: ',
  checkTxt: ' Please check your',
  spamMail: ' Spam mail',
  resend: 'Resend',
  mailReceiveLabel: 'Didn’t receive an email?',
  signIn: 'Sign in',
};
export const ForgotPasswordLabels = {
  email: 'Email',
  resend: 'Resend',
  send: 'Send',
  signIn: 'Sign in',
  mailReceiveLabel: 'Didn’t receive an email?',
  forgotPasswordLabel: 'Forgot password?',
  forgotPasswordContent:
    'Enter the e-mail address associated with your account and we’ll send you a link to reset your password',
};

export const ResetPasswordLabels = {
  resetPassword: 'Reset password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  changePassword: 'Change password',
  signInwithNewPw: 'Sign in with your new password',
  signIn: 'Sign in',
};

export const Sidebar = {
  accounts: 'Accounts & opportunities',
  accountsEngagements: 'Account Engagements',
  campaigns: 'Campaigns',
  content: 'Content',
  sales: 'Sales Enablement',
  report: 'Report',
  setup: 'Setup',
  assets: 'Assets',
  assetCollection: 'Asset Collections',
  salesHub: 'Sales Hub',
  salesMotion: 'Sales Motions',
  salesContact: 'Sales Contacts',
  settings: 'Partnership Settings',
};

export const AccountSetupLabels = {
  accountSetupHeader: `Let's set up your account`,
  accountSetupSubHeader: 'Complete the following steps to get started',
  addPartnership: 'Add a Partnership',
  addPartnershipDescription:
    'Enter the company information about your Partnership',
  addPartnershipButtonLabel: 'Create Partnership',
  uploadAssets: 'Upload Assets',
  uploadAssetsDescription:
    'Upload sales and marketing content on your Partnership',
  uploadAssetsButtonLabel: `Upload Assets`,
  createAssetCollection: 'Create Asset Collection',
  createAssetCollectionDescription:
    'Organize your Assets into content playlists covering a solution or theme',
  createAssetCollectionButtonLabel: `Create Asset Collection`,
  configureSalesHub: 'Configure Sales Hub',
  configureSalesHubDescription:
    'Define the sales enablement content for internal sales reps',
  configureSalesHubButtonLabel: `Create Sales Hub`,
  createABMCampaign: 'Create an ABM Campaign',
  createABMCampaignDescription: 'Set up Sales Motion for target accounts',
  createABMCampaignButtonLabel: `Create Campaigns`,
  accountEngagement: 'Account Engagements',
  accountTargetDescription:
    'Define your joint account targets and sales Opportunities',
  accountEngagementButtonLabel: `Create Accounts`,
  createSalesMotion: 'Create a Sales Motion',
  createSalesMotionButtonLabel: 'Create Sales Motion',
};

export const CreatePartnershipStepperLabels = {
  step1: 'Step 1',
  step2: 'Step 2',
  step3: 'Step 3',
  step4: 'Step 4',
};

export const CreatePartnershipLabels = {
  partnershipInfoTitle: 'Enter the information of the Partnership',
  partnershipName: 'Partnership name',
  websiteSubDomainName: 'Content hub website subdomain name',
  websiteSubDomainNameLabel: 'Subdomain name',
  whitelistedDomainLabel: 'Whitelisted domains',
  whitelistedDomain: 'Whitelisted domains',
  domainEndPoint: '.cosell.partners',
  favicon: 'Upload favicon',
};

export const CompanyInfoLabels = {
  companyInfoTitle: 'Enter your company information',
  companyName: 'Company name',
  companyAddress: 'Company address',
  companyWebsite: 'Company website',
  city: 'City',
  country: 'Country',
  privacyPolicyURL: 'Privacy policy URL',
  siteTermsURL: 'Site terms URL',
  cookiePolicy: 'Cookie policy',
  companyLogo: 'Company logo',
  state: 'State',
  zipCode: 'Zip code',
};

export const CompanyPartnerInfoLabels = {
  companyPartnerInfoTitle: 'Enter partner company information',
  partnerCompanyName: 'Partner company name',
  partnerCompanyLogo: 'Partner company logo',
  partnerCompanyLogoLabel: 'Upload logo',
  partnerCompanyPrivacyPolicyURL: 'Partner company privacy policy URL',
  partnerCompanyPrivacyPolicyURLLabel: 'Privacy policy URL',
  partnerCompanySiteTermsURL: 'Partner company site terms URL',
  partnerCompanySiteTermsURLLabel: 'Site terms URL',
  partnerCompanyCookiePolicy: 'Partner company cookie policy',
  partnerCompanyCookiePolicyLabel: 'Cookie policy',
};

export const PartnerShipCoordinatorInfoLabels = {
  partnershipCoordinatorInfoTitle: 'Enter partnership coordinator information',
  coordinatorname: 'Coordinator name',
  coordinatornameLabel: 'Co - ordinator name',
  email: 'Email',
  role: 'Role',
  roleLabel: 'Select role',
  companyName: 'Company name',
};

export const PreviewPartnershipLabels = {
  titleLabel: 'Update Partnership',
  cancelButtonLabel: 'Cancel',
  saveButtonLabel: 'Save',
  partnershipInfoLabel: 'Partnership information',
  partnershipNameLabel: 'Partnership name',
  webSubdomainNameLabel: 'Content hub website subdomain name',
  favicon: 'Upload favicon',
  endAdornmentTextLabel: '.cosell.com',
  companyInfoLabel: 'Company information',
  companyNameLabel: 'Company name',
  companyLogoLabel: 'Company logo',
  companyAddressLabel: 'Company address',
  companyWebsiteLabel: 'Company website',
  cityLabel: 'City',
  stateLabel: 'State',
  countryLabel: 'Country',
  zipLabel: 'Zip code',
  privacyPolicyURLLabel: 'Privacy policy URL',
  siteTermsURLLabel: 'Site terms URL',
  cookiePolicyLabel: 'Cookie policy',
  partnerCompanyInfoLabel: 'Partner company information',
  partnerCompanyNameLabel: 'Partner company name',
  partnerCompanySiteTermsURLLabel: 'Partner company site terms URL',
  partnerCompanyLogoLabel: 'Partner company logo',
  partnerCompanyCookiePolicyLabel: 'Partner company cookie policy',
  partnerCompanyPrivacyPolicyURLLabel: 'Partner company privacy policy URL',
  partnershipTeamLabel: 'Partnership team',
  addCollaboratorButtonLabel: 'Add collaborator',
  snackbarMsg: 'Partnership created successfully',
  snackbarUpdateMsg: 'Partnership updated successfully',
  snackbarDeleteMsg: 'Partnership deleted successfully',
  webSubDomainNamePlaceholder: 'Subdomain name',
  companyLogoPlaceholder: 'Upload logo',
  fileErrorMessage: 'Invalid file format. Please use jpg, png, or svg.',
  whitelistedDomain: 'Whitelisted domains',
  domainEndPoint: '.cosell.partners',
};

export const uploadAssetsLabels = {
  manageAssets: 'Manage Assets',
  addAsset: 'Add Assets',
  searchAsset: 'Search Assets',
  filterByAccessType: 'Filter by access type',
  filterByDocType: 'Filter by document type',
  name: 'Name',
  docType: 'Document type',
  accessType: 'Access type',
  tags: 'Tags',
  uploadTitle: 'Upload Asset',
  assetInfo: 'Asset information',
  assetName: 'Asset name',
  uploadFile: 'Upload file',
  status: 'Status',
  cancel: 'Cancel',
  save: 'Save',
  active: 'Active',
  inActive: 'Inactive',
  deleteAsset: 'Delete Asset',
  updateAsset: 'Update Asset',
  search: 'Search',
  size: 'Size',
  fileErrorMessage: 'Invalid file format. Please use jpg, png, or svg.',
  noRecords: 'No results found',
  confirmDeleteAsset:
    'Are you sure you want to delete the Asset? Assets mapped to any Asset Collections will be removed',
};

export const errorMessageLabels = {
  companyName: 'Company name is required',
  companyAddress: 'Company address is required',
  companyWebsite: 'Company website is required',
  city: 'City is required',
  invalidCity: 'Invalid city',
  country: 'Country is required',
  invalidCountry: 'Invalid country',
  state: 'State is required',
  zipCode: 'Zip code is required',
  invalidZipCode: 'Invalid zip code',
  invalidState: 'Invalid state',
  partnerCompanyName: 'Partner company name is required',
  partnershipName: 'Partnership name is required',
  subDomain: 'Subdomain name is required',
  websiteSubDomain: 'Subdomain name is required',
  privacyPolicy: 'Privacy policy URL is required',
  cookiePolicy: 'Cookie policy is required',
  siteTermsURL: 'Site terms URL is required',
  partnerCompanySiteTermsURL: 'Partner company site terms URL is required',
  partnerCompanyCookiePolicy: 'Partner company cookie policy is required',
  partnerCompanyPrivacyPolicyURL:
    'Partner company privacy policy URL is required',
  email: 'Email is required',
  validEmail: 'Enter a valid email',
  invalidURL: 'Invalid URL',
  fileErrorMessage: 'Invalid file format. Please use jpg, png, or svg.',
  whitelistedDomains: 'Whitelisted domain is required',
};

export const MyAccountLabels = {
  firstName: 'First name',
  lastName: 'Last name',
  profileImage: 'Profile image',
  changeImage: 'Change image',
  uploadImage: 'Upload image',
  emailAddress: 'Email address',
  changePassword: 'Change password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  currentPassword: 'Current password',
  cancel: 'Cancel',
  update: 'Update',
  successMsg: 'Account details updated successfully',
  successProfileMsg: 'Profile updated successfully',
  fileErrorMessage: 'Invalid file format. Please upload a image file',
};
export const SalesHubSiteProfileLabels = {
  firstName: 'First name',
  lastName: 'Last name',
  profileImg: 'Profile image',
  fileErrorMessage: 'Invalid file format. Please upload a image file',
  changeImage: 'Change image',
  uploadImage: 'Upload image',
  companyName: 'Company name',
  role: 'Role',
  salesRegion: 'Sales region',
  emailAddress: 'Email address',
  changePassword: 'Change password',
  newPassword: 'New password',
  confirmPassword: 'Confirm password',
  currentPassword: 'Current password',
  deleteProfile: 'Delete profile',
  cancel: 'Cancel',
  update: 'Update',
  successMsg: 'Account details updated successfully',
  successProfileMsg: 'Profile updated successfully',
  profileDeleteSuccessMsg: 'Profile deleted successfully',
  deleteConfirmation: 'Are you sure you want to delete the Sales Rep profile?',
  requestPassword: 'Enter the Sales Rep password to delete the account',
  delete: 'Delete',
  password: 'Password',
};

export const createAccount = {
  companyName: 'Company name',
  companyLogo: 'Company logo',
  domainName: 'Domain name',
  industry: 'Industry',
  targetBuyerTitles: 'Target buyer titles',
  accessType: 'Access type',
  accountType: 'Account type',
  teamCadence: 'Team check-in cadence',
  salesMotion: 'Sales Motion',
  headerText: 'Header text',
  subHeaderText: 'Sub header text',
  headerImage: 'Header image',
  headerImageWeb: 'Header image(Web)',
  headerImageMobile: 'Header image (Mobile)',
  fontColor: 'Font color',
  fontStyle: 'Font style',
  ctaName: 'CTA name',
  ctaImage: 'CTA image',
  embeddedCode: 'Embedded code',
  ctaDescription: 'Description',
  cadenceId: 'Every',
  salesHubSiteSuccessMsg: 'Account updated successfully',
  salesHubSiteCreateSuccessMsg: 'Account created  successfully',
  createdBy: 'Created by',
  filterBySalesMotion: 'Filter by Sales Motion',
  filterByStatus: 'Filter by status',
  status: 'Status',
  companyWebsite: 'Company website',
  servicePartnerInvloved: 'Service partner involved',
  servicePartnerName: 'Service provider name',
  servicePartnerLogo: 'Service provider logo',
  accountTeamLabel: 'Account team',
  enterEmailLabel: 'Enter email',
  seperateByCommaHelperText: 'Separate multiple emails with a comma(,)',
  TargetBuyerHelperText: 'Press enter to add target buyer titles',
  salesOpportunities: 'Sales Opportunities',
  opportunityName: 'Opportunity name',
  salesStage: 'Sales stage',
  createdDate: 'Created date',
  estimatedCloseDate: 'Estimated close date',
  estimatedDealAmount: 'Estimated deal amount',
  addSalesOpportunity: 'Add Sales Opportunity',
  removeOpportunity: 'Remove Opportunity',
  createSalesOpportunity: 'Create Sales Opportunity',
  updateSalesOpportunity: 'Update Sales Opportunity',
  description: 'Description',
  contentEngagement: 'Content engagement',
  siteSessions: 'Site sessions',
  uniqueVisitors: 'Unique visitors',
  totalSiteTime: 'Total site time',
  averageSessionTime: 'Average session time',
  ctaPageViews: 'CTA page views',
  ctaCompletion: 'CTA completion',
  totalAssetsViewed: 'Total assets viewed',
  knownContacts: 'Known contacts',
  engagementByAsset: 'Engagement by Asset',
  assetName: 'Asset name',
  timeOnAsset: 'Time on asset',
  uniqueViews: 'Unique views',
  views: 'Views',
  siteVisitors: 'Site visitors',
  visitor: 'Visitor',
  location: 'Location',
  lastVisit: 'Last visit',
  visits: 'Visits',
  timeOnSite: 'Time on site',
  ctaCompleted: 'CTA Completed',
  assetsViewed: 'Assets viewed',
  ctaStaticForm: 'Static form',
  ctaFormHeader: 'Form header',
  ctaKeyName: 'Key name',
  ctaDisplayName: 'Display name',
  export: 'Export',
};

export const createAccountDropdown = {
  general: 'General',
  siteLayout: 'Site layout details',
  calloutSection1: 'Call out section #1',
  calloutSection2: 'Call out section #2',
  sollutinNarrative: 'Asset Collections',
  cta: 'CTA',
  accountsTeam: 'Accounts team',
  userInformation: 'User information',
  salesOpportunities: 'Sales Opportunities',
};

export const salesHubTableLabels = {
  accountName: 'Account name',
  accountType: 'Account type',
  industry: 'Industry',
  salesMotion: 'Sales Motion',
  status: 'Status',
  createdBy: 'Created by',
};

export const salesHubSiteTitle = {
  cardTile: 'Recommended content for you',
  tableTile: 'Account Engagements',
  buttonCreate: ' Create Account',
  inviteAccTeam: 'Invite Account Team',
  noAssetCollection: 'No Asset Collection is available',
};

export const AssetCollectionLabels = {
  title: 'Asset Collections',
  previewTitle: 'Asset Collection preview',
  formTitle: 'Create Asset Collection',
  updateTitle: 'Update Asset Collection',
  deleteTitle: 'Delete Asset Collection',
  createButton: 'Create new',
  general: 'General',
  name: 'Name',
  description: 'Description',
  thumbnailImage: 'Thumbnail image',
  tags: 'Tags',
  assets: 'Assets',
  add: 'Add',
  addAssets: 'Add Assets',
  manageAssets: 'Manage Assets',
  noAssetsMessage: 'No Assets added to the Asset Collection',
  learnMore: 'Learn more',
};

export const DialogBoxLabels = {
  deleteDialogAssetCollectPrimaryContent: 'Delete Asset Collection',
  deleteDialogAssetCollectSecondaryContent:
    'Are you sure you want to delete the Asset Collection ?',
  deleteDialogSecondaryButton: 'Cancel',
  deleteDialogPrimaryButton: 'Delete',
  deleteAssetCollectMsg: 'Asset Collection deleted successfully',
  deleteDialogSalesMotionPrimaryContent: 'Delete Sales Motion',
  deleteDialogSalesMotionSecondaryContent:
    'Are you sure you want to delete the Sales Motion ?',
  deleteSalesMotionMsg: 'Sales Motion deleted successfully',
};
export const SalesHubLabels = {
  titleLabel: 'Sales Hub',
  previewButton: 'Preview',
  saveButton: 'Save',
  cancel: 'Cancel',
  salesHubLayout: 'Sales Hub layout',
  headerText: 'Header text',
  subHeaderText: 'Sub header text',
  headerImg: 'Header image',
  headerImgField: 'Header image',
  fontColor: 'Font color',
  selectFontColor: 'Font color',
  fontFamily: 'Font family',
  selectFontFamily: 'Font family',
  assetCollection: 'Asset Collections',
  addAssetCollection: 'Add Asset Collection',
  addAssetCollectionButton: 'Add Asset Collection',
  manageAssetCollectButtonLabel: 'Manage Asset Collection',
  noAssetMsg: 'No Asset Collections mapped to the Sales Hub',
};

export const ManageAssetCollectionLabels = {
  titleLabel: 'Sales Hub Asset Collections',
  manageAssetCollection: 'Manage Asset Collections',
  addNew: 'Add new',
  remove: 'Remove',
  cancel: 'Cancel',
  save: 'Save',
  tableName: 'Name',
  tableNoOfAssets: 'Number of Assets',
  tableTags: 'Tags',
  viewAssetCollections:
    'To view Asset Collections choose Sales Motion in site layout',
  noSalesMotionMapped: 'No Asset Collections mapped for this Sales Motion',
};

export const mailVerificationLabels = {
  signInLabel: 'To Sign in please click ',
  here: 'here',
  verifiedTxt: 'Your email address has been verified',
  thanksTxt: 'Thank you',
  cosellTeam: 'Symbio Team',
};

export const SalesMotionLabels = {
  title: 'Sales Motions',
  createSalesMotion: 'Create Sales Motion',
  deleteSalesMotion: 'Delete Sales Motion',
  createNew: 'Create new',
  addNew: 'Add new',
  remove: 'Remove',
  cancel: 'Cancel',
  save: 'Save',
  name: 'Name',
  description: 'Description',
  targetBuyerTitles: 'Target buyer titles',
  TargetBuyerHelperText: 'Press enter to add target buyer titles',
  domainName: 'Domain name',
  domainEndAdornment: '.lp.parterns',
  headerTxt: 'Header text',
  subHeaderTxt: 'Sub header text',
  headerImage: 'Header image',
  headerImageWeb: 'Header image (Web)',
  headerImageMobile: 'Header image (Mobile)',
  fontColor: 'Font color',
  fontStyle: 'Font style',
  ctaName: 'CTA name',
  ctaImage: 'CTA image',
  embeddedCode: 'Embedded code',
  salesMotionSuccessMsg: 'Sales Motion created successfully',
  salesMotionUpdateSuccessMsg: 'Sales Motion updated successfully',
  ctaDescription: 'Description',
  ctaStaticForm: 'Static form',
  ctaFormHeader: 'Form header',
  ctaKeyName: 'Key name',
  ctaDisplayName: 'Display name',
};
export const AccountsEngagementsLabels = {
  title: 'Account Engagements',
  deleteAccount: 'Delete Account',
  createAccount: 'Create Account',
  cancel: 'Cancel',
  confirmDeleteAccount: 'Are you sure you want to delete the Account ?',
  // deleteAccount: 'Delete sales hub account',
  inviteAccTeam: 'Invite Account Team',
  accountTeamSuccessMsg: 'User invited to the Account successfully',
  deleteAccountMsg: 'Account deleted successfully',
  deleteAccountTeamUser: 'Delete Account team user',
  confirmDeleteAccountTeamUser:
    'Are you sure you want to remove the Account team user ?',
  deleteAccountUser: 'Remove user',
  deleteAccountUserSuccessMsg: 'User removed successfully',
  resendSucessMsg: 'Email resent successfully',
  salesOpportunitiesSuccessMsg: 'Sales Opportunity created successfully',
  salesOpportunitiesupdateSuccessMsg: 'Sales Opportunity updated successfully',
  confirmDeleteSalesOpportunity:
    'Are you sure you want to remove the Sales Opportunity ?',
  deleteSalesOpportunity: 'Delete Sales Opportunity',
  deleteSalesOpportunitySuccessMsg: 'Sales Opportunity deleted successfully',
};
export const SalesRepFooterLabels = {
  siteUrl: 'Site Terms',
  privacyPolicyUrl: 'Privacy Policy',
  cookiePolicyUrl: ' Cookie Policy',
};

export const AccountTeamLabel = {
  title: 'Manage Account team',
  enterEmail: 'Enter email',
  firstName: 'First name',
  lastName: 'Last name',
  email: 'Email',
  role: 'Role',
  company: 'Company',
  inviteStatus: 'Invite status',
  manageAccountTeamLabel: 'Manage Account team',
  addUser: 'Add user',
  removeUser: 'Remove user',
};

export const campaignHubLabels = {
  contentForYou: ' Explore content curated just for you',
  viewContentLabel: 'View content',
  siteTerms: ' Site Terms',
  privacyPolicy: 'Privacy Policy',
  cookiePolicy: 'Cookie Policy',
  noAssetPreview: 'No Asset to preview',
  noAssetCollection: 'No Asset Collection is available',
  shareLink: 'Share',
};

export const campaignHubCtaLabels = {
  backLinkLabel: '< Back to the previous page',
  ctaTermPolicy:
    'By entering your information you agree to share it to be used in accordance with the respective privacy policies for both ',
};

export const previewImageLables = {
  companyLogo: 'COMPANY_LOGO',
  partnerCompanyLogo: 'PARTNER_COMPANY_LOGO',
  servicePartnerCompanyLogo: 'SERVICE_PARTNER_COMPANY_LOGO',
  siteLayoutImage: 'SITELAYOUT_HEADER_IMAGE',
  siteLayoutImageWeb: 'SITELAYOUT_HEADER_IMAGE_WEB',
  siteLayoutImageMobile: 'SITELAYOUT_HEADER_IMAGE_MOBILE',
  calloutOneImage: 'CALLOUT_SEC_ONE_HEADER_IMAGE',
  calloutTwoImage: 'CALLOUT_SEC_TWO_HEADER_IMAGE',
  ctaImage: 'CTA_IMAGE',
  salesHubImage: 'SALESHUB_HEADER_IMAGE',
  AssetCollectionImage: 'ASSET_COLLECTION_IMAGE',
  profileImage: 'PROFILE_IMAGE',
  favIcon: 'FAVICON',
};
export const accountContactsLabel = {
  contacts: 'Contacts',
  ip: 'IP',
  organization: 'Organization',
  TotalEngagedTime: 'Total engaged time',
  SiteSessions: 'Site sessions',
  TopAssetEngagement: 'Top Asset engagement',
  export: 'Export',
};
export const salesContactsLabel = {
  SalesContacts: 'Sales Contacts',
  export: 'Export',
  firstName: 'First name',
  lastName: 'Last name',
  role: 'Role',
  company: 'Company',
  email: 'Email',
  inviteStatus: 'Invite status',
  lastLogin: 'Last login',
  noRecordsFound: 'No records found',
};
